# Generated by Django 4.0 on 2021-12-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('complete', 'C'), ('pending', 'P'), ('delivered', 'D')], default='P', max_length=25)),
                ('created_at', models.DateField(auto_now=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
