# Generated by Django 4.0 on 2021-12-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('commented', 'CM'), ('completed', 'C'), ('deleted', 'D'), ('created', 'CRE')], max_length=250)),
                ('description', models.TextField()),
                ('action_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='auth.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_activity', to='task.activity'),
            preserve_default=False,
        ),
    ]
