# Generated by Django 4.0 on 2021-12-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_activity_alter_task_user_task_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_activity', to='task.activity'),
        ),
    ]
